# Generated by Django 4.1.7 on 2023-03-04 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0003_alter_answer_docs_alter_questions_docs_and_more'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books_model',
            name='catogery',
        ),
        migrations.AddField(
            model_name='books_model',
            name='catogery',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Questions.catogery'),
        ),
    ]
