# Generated by Django 4.1.7 on 2023-03-03 12:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnswerAccepted', models.BooleanField(default=False)),
                ('SatisfactionScore', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_number', models.CharField(max_length=225)),
                ('image', models.ImageField(upload_to='Transaction_Images_uploaded')),
                ('amount_of_reward_token', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('Status', models.CharField(choices=[('Submitted', 'Submitted'), ('Transacted', 'Transacted'), ('declined', 'Decline')], max_length=20)),
                ('date_of_decision', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
