# Generated by Django 4.1.7 on 2023-03-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reward', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_record',
            name='Status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Transacted', 'Transacted'), ('declined', 'Decline')], default='Submitted', max_length=20),
        ),
    ]
