# Generated by Django 4.1.7 on 2023-03-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reward', '0003_alter_transaction_record_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_record',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Transaction_Images_uploaded'),
        ),
    ]
