# Generated by Django 4.1.7 on 2023-03-03 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Reward',
            field=models.IntegerField(default=0),
        ),
    ]
