# Generated by Django 4.1.7 on 2023-03-03 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.application'),
        ),
    ]
