# Generated by Django 4.1.7 on 2023-03-04 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.application'),
        ),
    ]
