# Generated by Django 4.1.7 on 2023-03-04 04:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_user_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Resume',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
